nodeLinker: node-modules

packageExtensions:
  laravel-vite-plugin@*:
    dependencies:
      picocolors: ^1.0.0
  vue-advanced-chat@*:
    peerDependenciesMeta:
      jquery:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true

yarnPath: .yarn/releases/yarn-3.3.0.cjs
