nodeLinker: node-modules

packageExtensions:
  vue-advanced-chat@*:
    peerDependenciesMeta:
      jquery:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true

yarnPath: .yarn/releases/yarn-3.6.3.cjs
